import * as fs from 'fs';
import * as path from 'path';
import AdmZip from 'adm-zip';

export interface ZipOptions {
  jobId: string;
  format: 'html' | 'react' | 'nextjs';
  sourceUrl: string;
  title?: string;
}

// ── README template ──────────────────────────────────────────────────────────
function buildReadme(opts: {
  sourceUrl: string;
  format: 'html' | 'react' | 'nextjs';
  title: string;
  exportedAt: string;
  fileList: string[];
}): string {
  const { sourceUrl, format, title, exportedAt, fileList } = opts;

  const formatLabel =
    format === 'html' ? 'Static HTML / CSS / JS' :
    format === 'react' ? 'React TSX Components' :
    'Next.js 15 (App Router) + Tailwind CSS';

  const deploySection =
    format === 'html'
      ? `## Deploying the Site

### Option 1 — Netlify (drag and drop)
1. Go to <https://netlify.com> and sign in.
2. Click **Add new site** > **Deploy manually**.
3. Drag the entire unzipped folder (containing index.html) onto the upload area.
4. Done — Netlify gives you a live URL instantly.

### Option 2 — Cloudflare Pages
1. Unzip the export so index.html is at the folder root.
2. Go to <https://pages.cloudflare.com> > Create a project > Upload assets.
3. Upload the folder. Leave the build command blank.
4. Add your custom domain in the Pages dashboard.

### Option 3 — Vercel (CLI)
\`\`\`bash
npx vercel@latest login
npx vercel@latest --prod
\`\`\`
Set **Framework Preset** to "Other" and leave the build command empty.

### Option 4 — cPanel / FTP / VPS
Upload all files in this folder to your \`public_html\` (or web root) directory
via FTP. Make sure \`index.html\` is at the top level.

### Option 5 — Local preview
Always serve over HTTP — do not open index.html directly via \`file://\`.

\`\`\`bash
# Python (built-in)
python -m http.server 8080

# Node.js
npx serve .
\`\`\`
Then open <http://localhost:8080> in your browser.`
      : `## Running the Next.js project

### Install dependencies
\`\`\`bash
npm install
\`\`\`

### Start dev server
\`\`\`bash
npm run dev
\`\`\`
Open <http://localhost:3000>.

### Build for production
\`\`\`bash
npm run build
npm run start
\`\`\`

### Deploy to Vercel
\`\`\`bash
npx vercel@latest --prod
\`\`\`

### Deploy to Netlify
Use the Netlify CLI or connect your Git repo in the Netlify dashboard.
Set the build command to \`npm run build\` and publish directory to \`.next\`.`;

  const editingSection =
    format === 'html'
      ? `## Editing the Export

| File | Purpose |
|------|---------|
| \`index.html\` | Full page markup — edit copy, structure, and links here |
| \`styles.css\` | All consolidated CSS — safe to edit or extend |
| \`script.js\` | Concatenated JS — minified; best to rebuild from source |
| \`assets/images/\` | Downloaded images — replace as needed |
| \`assets/fonts/\` | Downloaded web fonts — can be swapped for system fonts |

> **Tip:** Open this folder in VS Code, make your edits, and preview locally
> with \`npx serve .\` before deploying.`
      : `## Project structure

\`\`\`
app/
  layout.tsx        Root layout with metadata
  page.tsx          Main page composing all section components
  globals.css       Base + extracted styles (Tailwind v4)
components/
  Navbar.tsx        Auto-generated section component
  Hero.tsx          Auto-generated section component
  ...               (one file per detected section)
public/
  assets/           All downloaded images and fonts
package.json
next.config.mjs
tsconfig.json
\`\`\`

> Components are generated from the crawled DOM. Review and clean up
> any hashed class names before shipping to production.`;

  return `# ${title}

Exported by **SiteCompiler** — website source code exporter.

- **Source URL:** ${sourceUrl}
- **Export format:** ${formatLabel}
- **Exported at:** ${exportedAt}

---

${editingSection}

---

${deploySection}

---

## File listing

\`\`\`
${fileList.join('\n')}
\`\`\`

---

## Legal notice

This export was created for personal use, migration, and development purposes.
The exported code is a faithful reconstruction of the published site's source.
Ensure you have the right to host and distribute the site content.

Generated by [SiteCompiler](https://github.com/sitecompiler) — website exporter.
`;
}

// ── Recursively collect all files ─────────────────────────────────────────────
function collectFiles(folder: string, base: string = ''): string[] {
  const out: string[] = [];
  for (const entry of fs.readdirSync(folder, { withFileTypes: true })) {
    const rel = base ? `${base}/${entry.name}` : entry.name;
    if (entry.isDirectory()) {
      out.push(...collectFiles(path.join(folder, entry.name), rel));
    } else {
      out.push(rel);
    }
  }
  return out;
}

function addFolderToZip(zip: AdmZip, folderPath: string, zipBasePath: string = ''): void {
  for (const entry of fs.readdirSync(folderPath, { withFileTypes: true })) {
    const fullPath = path.join(folderPath, entry.name);
    const zipPath = zipBasePath ? `${zipBasePath}/${entry.name}` : entry.name;
    if (entry.isDirectory()) {
      addFolderToZip(zip, fullPath, zipPath);
    } else {
      zip.addFile(zipPath, fs.readFileSync(fullPath));
    }
  }
}

// ── Main export ───────────────────────────────────────────────────────────────
export async function createJobZip(options: ZipOptions): Promise<string> {
  const { jobId, format, sourceUrl, title = 'Exported Site' } = options;

  const exportsDir = path.resolve(/* turbopackIgnore: true */ process.cwd(), 'exports', jobId);
  const targetSubDir = format === 'html' ? 'html-export' : 'nextjs-export';
  const sourceFolder = path.join(exportsDir, 'output', targetSubDir);

  if (!fs.existsSync(sourceFolder)) {
    throw new Error(`Output folder not found: ${sourceFolder}`);
  }

  const zipPath = path.join(exportsDir, 'download.zip');
  if (fs.existsSync(zipPath)) fs.unlinkSync(zipPath);

  // 1. Build file listing for README
  const fileList = collectFiles(sourceFolder);

  // 2. Write README.md into the output folder (it will be included in the ZIP)
  const readmePath = path.join(sourceFolder, 'README.md');
  const readme = buildReadme({
    sourceUrl,
    format,
    title,
    exportedAt: new Date().toUTCString(),
    fileList: [...fileList, 'README.md'],
  });
  fs.writeFileSync(readmePath, readme, 'utf-8');

  // 3. Create ZIP — all files at root level of the archive
  const zip = new AdmZip();
  addFolderToZip(zip, sourceFolder, '');
  zip.writeZip(zipPath);

  const stats = fs.statSync(zipPath);
  console.log(`ZIP created: ${zipPath} (${(stats.size / 1024).toFixed(1)} KB, ${fileList.length + 1} files)`);

  return zipPath;
}
