version: 2
updates:
  # Maintain npm dependencies for root Next.js & backend server
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 30
    commit-message:
      prefix: "chore(deps)"
    labels:
      - "dependencies"
      - "automated"

  # Maintain GitHub Actions workflow dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "ci(actions)"
    labels:
      - "ci"
      - "automated"
