import * as fs from 'fs';
import * as path from 'path';
import prettier from 'prettier';
import { generateComponentFromSection, sanitizeComponentName, GeneratedComponent } from '../react/jsx-builder';
import { DetectedSection } from '../../detector/section-detector';
import { ExtractedMeta } from '../../crawler/types';

export interface NextJsBuildOptions {
  jobId: string;
  baseUrl: string;
  sections: DetectedSection[];
}

export interface NextJsBuildResult {
  outputDir: string;
  components: GeneratedComponent[];
  pagePath: string;
  layoutPath: string;
}

export async function buildNextJsExport(options: NextJsBuildOptions): Promise<NextJsBuildResult> {
  const { jobId, sections } = options;

  const exportsDir = path.resolve(/* turbopackIgnore: true */ process.cwd(), 'exports', jobId);
  const rawDir = path.join(exportsDir, 'raw');
  const outputDir = path.join(exportsDir, 'output', 'nextjs-export');
  const appDir = path.join(outputDir, 'app');
  const componentsDir = path.join(outputDir, 'components');
  const publicDir = path.join(outputDir, 'public');

  [outputDir, appDir, componentsDir, publicDir].forEach((d) => fs.mkdirSync(d, { recursive: true }));

  // 1. Copy Assets to public/assets
  const rawAssetsDir = path.join(exportsDir, 'output', 'html-export', 'assets');
  if (fs.existsSync(rawAssetsDir)) {
    fs.cpSync(rawAssetsDir, path.join(publicDir, 'assets'), { recursive: true });
  }

  // 2. Read HTML for section generation
  const rawHtml = fs.readFileSync(path.join(rawDir, 'page.html'), 'utf-8');

  // 3. Read Metadata
  let meta: ExtractedMeta = { title: 'Exported Site', canonicalUrl: null, metaTags: [], jsonLd: [] };
  const metaPath = path.join(rawDir, 'meta.json');
  if (fs.existsSync(metaPath)) {
    meta = JSON.parse(fs.readFileSync(metaPath, 'utf-8'));
  }

  // 4. Generate Section TSX Components with unique component names
  const generatedComponents: GeneratedComponent[] = [];
  const nameCounts: Record<string, number> = {};

  let index = 1;
  for (const section of sections) {
    let baseName = sanitizeComponentName(section.name, index);
    if (!nameCounts[baseName]) {
      nameCounts[baseName] = 1;
    } else {
      nameCounts[baseName]++;
      baseName = `${baseName}${nameCounts[baseName]}`;
    }

    const comp = await generateComponentFromSection(section, index++, rawHtml, baseName);
    const destPath = path.join(outputDir, comp.filePath);
    fs.mkdirSync(path.dirname(destPath), { recursive: true });
    fs.writeFileSync(destPath, comp.code, 'utf-8');
    generatedComponents.push(comp);
  }

  // 5. Generate app/page.tsx composing all section components
  const imports = generatedComponents
    .map((c) => `import ${c.componentName} from '@/components/${c.componentName}';`)
    .join('\n');

  const componentTags = generatedComponents.map((c) => `      <${c.componentName} />`).join('\n');

  let pageCode = `
import React from 'react';
${imports}

export default function HomePage() {
  return (
    <main className="min-h-screen">
${componentTags}
    </main>
  );
}
  `.trim();

  try {
    pageCode = await prettier.format(pageCode, { parser: 'typescript', singleQuote: true });
  } catch {}

  const pagePath = path.join(appDir, 'page.tsx');
  fs.writeFileSync(pagePath, pageCode, 'utf-8');

  // 6. Generate app/layout.tsx
  let layoutCode = `
import React from 'react';
import './globals.css';

export const metadata = {
  title: ${JSON.stringify(meta.title)},
  description: 'Reconstructed site generated by SiteCompiler',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="antialiased">{children}</body>
    </html>
  );
}
  `.trim();

  try {
    layoutCode = await prettier.format(layoutCode, { parser: 'typescript', singleQuote: true });
  } catch {}

  const layoutPath = path.join(appDir, 'layout.tsx');
  fs.writeFileSync(layoutPath, layoutCode, 'utf-8');

  // 7. Generate app/globals.css
  const consolidatedCssPath = path.join(exportsDir, 'output', 'html-export', 'styles.css');
  let globalsCss = '@import "tailwindcss";\n';
  if (fs.existsSync(consolidatedCssPath)) {
    globalsCss += fs.readFileSync(consolidatedCssPath, 'utf-8');
  }
  fs.writeFileSync(path.join(appDir, 'globals.css'), globalsCss, 'utf-8');

  // 8. Generate package.json
  const packageJson = {
    name: 'sitecompiler-exported-site',
    version: '1.0.0',
    private: true,
    scripts: {
      dev: 'next dev',
      build: 'next build',
      start: 'next start',
    },
    dependencies: {
      next: '^15.0.0',
      react: '^19.0.0',
      'react-dom': '^19.0.0',
    },
    devDependencies: {
      '@tailwindcss/postcss': '^4.0.0',
      tailwindcss: '^4.0.0',
      typescript: '^5.0.0',
      '@types/node': '^20.0.0',
      '@types/react': '^19.0.0',
      '@types/react-dom': '^19.0.0',
    },
  };
  fs.writeFileSync(path.join(outputDir, 'package.json'), JSON.stringify(packageJson, null, 2), 'utf-8');

  // 9. Generate configuration files
  const nextConfig = `
/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
};

export default nextConfig;
  `.trim();
  fs.writeFileSync(path.join(outputDir, 'next.config.mjs'), nextConfig, 'utf-8');

  const tsConfig = {
    compilerOptions: {
      target: 'ES2017',
      lib: ['dom', 'dom.iterable', 'esnext'],
      allowJs: true,
      skipLibCheck: true,
      strict: true,
      noEmit: true,
      esModuleInterop: true,
      module: 'esnext',
      moduleResolution: 'bundler',
      resolveJsonModule: true,
      isolatedModules: true,
      jsx: 'preserve',
      incremental: true,
      paths: {
        '@/*': ['./*'],
      },
    },
    include: ['next-env.d.ts', '**/*.ts', '**/*.tsx'],
    exclude: ['node_modules'],
  };
  fs.writeFileSync(path.join(outputDir, 'tsconfig.json'), JSON.stringify(tsConfig, null, 2), 'utf-8');

  return {
    outputDir,
    components: generatedComponents,
    pagePath,
    layoutPath,
  };
}
